version: '3' # Version of docker-compose
services:
  # my-app:
  # image: ${docker-registry}/my-app:1.0
  # ports:
  # - 3000:3000
  mongodb: # Container name
    image: mongo 
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always # fixes MongoNetworkError when mongodb is not ready when mongo-express starts
    depends_on:
      - "mongodb"
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
  my-app:
    image: my-app:1.0
    depends_on:
      - "mongodb"
      - "mongo-express"
    ports:
      - 3000:3000
    environment: 
      -  MONGO_DB_USERNAME=admin
      -  MONGO_DB_PWD=password
    restart: always
    links:
      - "mongodb"
volumes:
  mongo-data:
    driver: local
